In [1]:
import torch
from torch import nn

# Code

In [2]:
class LogisticRegression(nn.Module):
    def __init__(self, m):
        super().__init__()
        self.stack = nn.Sequential(
            nn.Linear(m, 1),
            nn.Sigmoid()
            )

    def forward(self, X):
        return self.stack(X).reshape(-1)

In [4]:
def train(X_train, y_train, loss_fn, optimizer):
    y_pred = model(X_train)
    loss = loss_fn(y_pred, y_train)
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()

In [5]:
# Test on a simple dataset
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

from sklearn.preprocessing import StandardScaler

X, y = make_classification(n_samples=1000, n_features=10, n_informative=8,
                         n_redundant=2, n_classes=2, random_state=42)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Add normalization
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

X_train = torch.as_tensor(X_train, dtype=torch.float32)
y_train = torch.as_tensor(y_train, dtype=torch.float32)
X_test = torch.as_tensor(X_test, dtype=torch.float32)
y_test = torch.as_tensor(y_test, dtype=torch.double)

In [6]:
model = LogisticRegression(X_train.shape[1])
loss_fn = nn.BCELoss()
#optimizer = torch.optim.SGD(model.parameters(), lr=0.01)
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

In [ ]:
num_epochs = 1000
for epoch in range(num_epochs):
    train(X_train, y_train, loss_fn, optimizer)
    if epoch % 100 == 0:
        loss = loss_fn(model(X_train), y_train).item()
        print(f"epoch {epoch}:", loss) 
        #print(loss)

In [ ]:
with torch.no_grad():
    y_pred_probs = model(X_test)
    y_pred = torch.as_tensor(y_pred_probs >= 0.5, dtype=int)
    accuracy = torch.mean(y_pred == y_test, dtype=torch.float32)
    print(f"Test Accuracy: {accuracy:.3f}")

In [ ]:
# Compare with sklearn
from sklearn.linear_model import LogisticRegression as SklearnLR
sklearn_model = SklearnLR()
sklearn_model.fit(X_train, y_train)
sklearn_acc = sklearn_model.score(X_test, y_test)
print(f"Sklearn Accuracy: {sklearn_acc:.3f}")

# Scratchpad

In [8]:
for p in model.parameters():
    print(p)

Parameter containing:
tensor([[-0.3069, -0.2260,  0.1183, -0.0345, -0.0469,  0.1373,  0.0226, -0.3104,
          0.1331,  0.2305]], requires_grad=True)
Parameter containing:
tensor([-0.1669], requires_grad=True)


In [9]:
p

Parameter containing:
tensor([-0.1669], requires_grad=True)

In [11]:
p.grad

In [ ]:
model

In [ ]:
help(model.parameters)